/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationAuditRouteImport } from './routes/validation-audit'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResultEntryRouteImport } from './routes/result-entry'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckResultRouteImport } from './routes/check-result'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyResultCodeRouteImport } from './routes/verify-result.$code'
import { Route as StudentServicesRouteImport } from './routes/student.services'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentResultPinsRouteImport } from './routes/student.result-pins'
import { Route as StudentRegisterRouteImport } from './routes/student.register'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPasswordRouteImport } from './routes/student.password'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentCarryoversRouteImport } from './routes/student.carryovers'
import { Route as ResultPinCallbackRouteImport } from './routes/result-pin.callback'
import { Route as ResultPinBuyRouteImport } from './routes/result-pin.buy'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as LecturerLoginRouteImport } from './routes/lecturer.login'
import { Route as LecturerEntryRouteImport } from './routes/lecturer.entry'
import { Route as LecturerDashboardRouteImport } from './routes/lecturer.dashboard'
import { Route as FacultyTranscriptsRouteImport } from './routes/faculty.transcripts'
import { Route as FacultyStudentsRouteImport } from './routes/faculty.students'
import { Route as FacultyResultsRouteImport } from './routes/faculty.results'
import { Route as FacultyResultEntryRouteImport } from './routes/faculty.result-entry'
import { Route as FacultyRegistrationLinksRouteImport } from './routes/faculty.registration-links'
import { Route as FacultyLoginRouteImport } from './routes/faculty.login'
import { Route as FacultyDeptAdminsRouteImport } from './routes/faculty.dept-admins'
import { Route as FacultyDashboardRouteImport } from './routes/faculty.dashboard'
import { Route as FacultyCoursesRouteImport } from './routes/faculty.courses'
import { Route as FacultyCarryoversRouteImport } from './routes/faculty.carryovers'
import { Route as DeptAdminLoginRouteImport } from './routes/dept-admin.login'
import { Route as DeptAdminLecturersRouteImport } from './routes/dept-admin.lecturers'
import { Route as DeptAdminDashboardRouteImport } from './routes/dept-admin.dashboard'
import { Route as DeptAdminAssignmentsRouteImport } from './routes/dept-admin.assignments'
import { Route as DeptAdminApprovalsRouteImport } from './routes/dept-admin.approvals'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api.paystack-webhook'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResultPinsRouteImport } from './routes/admin.result-pins'
import { Route as AdminRegistrationLinksRouteImport } from './routes/admin.registration-links'
import { Route as AdminProgrammesRouteImport } from './routes/admin.programmes'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminFacultyAdminsRouteImport } from './routes/admin.faculty-admins'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const ValidationAuditRoute = ValidationAuditRouteImport.update({
  id: '/validation-audit',
  path: '/validation-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultEntryRoute = ResultEntryRouteImport.update({
  id: '/result-entry',
  path: '/result-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckResultRoute = CheckResultRouteImport.update({
  id: '/check-result',
  path: '/check-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyResultCodeRoute = VerifyResultCodeRouteImport.update({
  id: '/verify-result/$code',
  path: '/verify-result/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServicesRoute = StudentServicesRouteImport.update({
  id: '/student/services',
  path: '/student/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultPinsRoute = StudentResultPinsRouteImport.update({
  id: '/student/result-pins',
  path: '/student/result-pins',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student/register',
  path: '/student/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPasswordRoute = StudentPasswordRouteImport.update({
  id: '/student/password',
  path: '/student/password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCarryoversRoute = StudentCarryoversRouteImport.update({
  id: '/student/carryovers',
  path: '/student/carryovers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultPinCallbackRoute = ResultPinCallbackRouteImport.update({
  id: '/result-pin/callback',
  path: '/result-pin/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultPinBuyRoute = ResultPinBuyRouteImport.update({
  id: '/result-pin/buy',
  path: '/result-pin/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const LecturerLoginRoute = LecturerLoginRouteImport.update({
  id: '/lecturer/login',
  path: '/lecturer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerEntryRoute = LecturerEntryRouteImport.update({
  id: '/lecturer/entry',
  path: '/lecturer/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerDashboardRoute = LecturerDashboardRouteImport.update({
  id: '/lecturer/dashboard',
  path: '/lecturer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyTranscriptsRoute = FacultyTranscriptsRouteImport.update({
  id: '/faculty/transcripts',
  path: '/faculty/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyStudentsRoute = FacultyStudentsRouteImport.update({
  id: '/faculty/students',
  path: '/faculty/students',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyResultsRoute = FacultyResultsRouteImport.update({
  id: '/faculty/results',
  path: '/faculty/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyResultEntryRoute = FacultyResultEntryRouteImport.update({
  id: '/faculty/result-entry',
  path: '/faculty/result-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRegistrationLinksRoute =
  FacultyRegistrationLinksRouteImport.update({
    id: '/faculty/registration-links',
    path: '/faculty/registration-links',
    getParentRoute: () => rootRouteImport,
  } as any)
const FacultyLoginRoute = FacultyLoginRouteImport.update({
  id: '/faculty/login',
  path: '/faculty/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDeptAdminsRoute = FacultyDeptAdminsRouteImport.update({
  id: '/faculty/dept-admins',
  path: '/faculty/dept-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyCoursesRoute = FacultyCoursesRouteImport.update({
  id: '/faculty/courses',
  path: '/faculty/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyCarryoversRoute = FacultyCarryoversRouteImport.update({
  id: '/faculty/carryovers',
  path: '/faculty/carryovers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminLoginRoute = DeptAdminLoginRouteImport.update({
  id: '/dept-admin/login',
  path: '/dept-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminLecturersRoute = DeptAdminLecturersRouteImport.update({
  id: '/dept-admin/lecturers',
  path: '/dept-admin/lecturers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminDashboardRoute = DeptAdminDashboardRouteImport.update({
  id: '/dept-admin/dashboard',
  path: '/dept-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminAssignmentsRoute = DeptAdminAssignmentsRouteImport.update({
  id: '/dept-admin/assignments',
  path: '/dept-admin/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminApprovalsRoute = DeptAdminApprovalsRouteImport.update({
  id: '/dept-admin/approvals',
  path: '/dept-admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack-webhook',
  path: '/api/paystack-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultPinsRoute = AdminResultPinsRouteImport.update({
  id: '/admin/result-pins',
  path: '/admin/result-pins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationLinksRoute = AdminRegistrationLinksRouteImport.update({
  id: '/admin/registration-links',
  path: '/admin/registration-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgrammesRoute = AdminProgrammesRouteImport.update({
  id: '/admin/programmes',
  path: '/admin/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultyAdminsRoute = AdminFacultyAdminsRouteImport.update({
  id: '/admin/faculty-admins',
  path: '/admin/faculty-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin/faculties',
  path: '/admin/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/audit-logs': typeof AuditLogsRoute
  '/check-result': typeof CheckResultRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programmes': typeof ProgrammesRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/registration-links': typeof AdminRegistrationLinksRoute
  '/admin/result-pins': typeof AdminResultPinsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/dept-admin/approvals': typeof DeptAdminApprovalsRoute
  '/dept-admin/assignments': typeof DeptAdminAssignmentsRoute
  '/dept-admin/dashboard': typeof DeptAdminDashboardRoute
  '/dept-admin/lecturers': typeof DeptAdminLecturersRoute
  '/dept-admin/login': typeof DeptAdminLoginRoute
  '/faculty/carryovers': typeof FacultyCarryoversRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/dept-admins': typeof FacultyDeptAdminsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/registration-links': typeof FacultyRegistrationLinksRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/entry': typeof LecturerEntryRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/result-pin/buy': typeof ResultPinBuyRoute
  '/result-pin/callback': typeof ResultPinCallbackRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/password': typeof StudentPasswordRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/result-pins': typeof StudentResultPinsRoute
  '/student/results': typeof StudentResultsRoute
  '/student/services': typeof StudentServicesRoute
  '/verify-result/$code': typeof VerifyResultCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/audit-logs': typeof AuditLogsRoute
  '/check-result': typeof CheckResultRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programmes': typeof ProgrammesRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/registration-links': typeof AdminRegistrationLinksRoute
  '/admin/result-pins': typeof AdminResultPinsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/dept-admin/approvals': typeof DeptAdminApprovalsRoute
  '/dept-admin/assignments': typeof DeptAdminAssignmentsRoute
  '/dept-admin/dashboard': typeof DeptAdminDashboardRoute
  '/dept-admin/lecturers': typeof DeptAdminLecturersRoute
  '/dept-admin/login': typeof DeptAdminLoginRoute
  '/faculty/carryovers': typeof FacultyCarryoversRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/dept-admins': typeof FacultyDeptAdminsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/registration-links': typeof FacultyRegistrationLinksRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/entry': typeof LecturerEntryRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/result-pin/buy': typeof ResultPinBuyRoute
  '/result-pin/callback': typeof ResultPinCallbackRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/password': typeof StudentPasswordRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/result-pins': typeof StudentResultPinsRoute
  '/student/results': typeof StudentResultsRoute
  '/student/services': typeof StudentServicesRoute
  '/verify-result/$code': typeof VerifyResultCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/audit-logs': typeof AuditLogsRoute
  '/check-result': typeof CheckResultRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/programmes': typeof ProgrammesRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/registration-links': typeof AdminRegistrationLinksRoute
  '/admin/result-pins': typeof AdminResultPinsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/dept-admin/approvals': typeof DeptAdminApprovalsRoute
  '/dept-admin/assignments': typeof DeptAdminAssignmentsRoute
  '/dept-admin/dashboard': typeof DeptAdminDashboardRoute
  '/dept-admin/lecturers': typeof DeptAdminLecturersRoute
  '/dept-admin/login': typeof DeptAdminLoginRoute
  '/faculty/carryovers': typeof FacultyCarryoversRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/dept-admins': typeof FacultyDeptAdminsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/registration-links': typeof FacultyRegistrationLinksRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/entry': typeof LecturerEntryRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/result-pin/buy': typeof ResultPinBuyRoute
  '/result-pin/callback': typeof ResultPinCallbackRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/password': typeof StudentPasswordRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/result-pins': typeof StudentResultPinsRoute
  '/student/results': typeof StudentResultsRoute
  '/student/services': typeof StudentServicesRoute
  '/verify-result/$code': typeof VerifyResultCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/audit-logs'
    | '/check-result'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/news'
    | '/programmes'
    | '/result-entry'
    | '/results'
    | '/schools'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/admin/news'
    | '/admin/programmes'
    | '/admin/registration-links'
    | '/admin/result-pins'
    | '/admin/settings'
    | '/api/paystack-webhook'
    | '/dept-admin/approvals'
    | '/dept-admin/assignments'
    | '/dept-admin/dashboard'
    | '/dept-admin/lecturers'
    | '/dept-admin/login'
    | '/faculty/carryovers'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/dept-admins'
    | '/faculty/login'
    | '/faculty/registration-links'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/lecturer/dashboard'
    | '/lecturer/entry'
    | '/lecturer/login'
    | '/news/$slug'
    | '/result-pin/buy'
    | '/result-pin/callback'
    | '/student/carryovers'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/login'
    | '/student/password'
    | '/student/profile'
    | '/student/register'
    | '/student/result-pins'
    | '/student/results'
    | '/student/services'
    | '/verify-result/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/audit-logs'
    | '/check-result'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/news'
    | '/programmes'
    | '/result-entry'
    | '/results'
    | '/schools'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/admin/news'
    | '/admin/programmes'
    | '/admin/registration-links'
    | '/admin/result-pins'
    | '/admin/settings'
    | '/api/paystack-webhook'
    | '/dept-admin/approvals'
    | '/dept-admin/assignments'
    | '/dept-admin/dashboard'
    | '/dept-admin/lecturers'
    | '/dept-admin/login'
    | '/faculty/carryovers'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/dept-admins'
    | '/faculty/login'
    | '/faculty/registration-links'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/lecturer/dashboard'
    | '/lecturer/entry'
    | '/lecturer/login'
    | '/news/$slug'
    | '/result-pin/buy'
    | '/result-pin/callback'
    | '/student/carryovers'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/login'
    | '/student/password'
    | '/student/profile'
    | '/student/register'
    | '/student/result-pins'
    | '/student/results'
    | '/student/services'
    | '/verify-result/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/audit-logs'
    | '/check-result'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/news'
    | '/programmes'
    | '/result-entry'
    | '/results'
    | '/schools'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/admin/news'
    | '/admin/programmes'
    | '/admin/registration-links'
    | '/admin/result-pins'
    | '/admin/settings'
    | '/api/paystack-webhook'
    | '/dept-admin/approvals'
    | '/dept-admin/assignments'
    | '/dept-admin/dashboard'
    | '/dept-admin/lecturers'
    | '/dept-admin/login'
    | '/faculty/carryovers'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/dept-admins'
    | '/faculty/login'
    | '/faculty/registration-links'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/lecturer/dashboard'
    | '/lecturer/entry'
    | '/lecturer/login'
    | '/news/$slug'
    | '/result-pin/buy'
    | '/result-pin/callback'
    | '/student/carryovers'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/login'
    | '/student/password'
    | '/student/profile'
    | '/student/register'
    | '/student/result-pins'
    | '/student/results'
    | '/student/services'
    | '/verify-result/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ApplyRoute: typeof ApplyRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CheckResultRoute: typeof CheckResultRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProgrammesRoute: typeof ProgrammesRoute
  ResultEntryRoute: typeof ResultEntryRoute
  ResultsRoute: typeof ResultsRoute
  SchoolsRoute: typeof SchoolsRoute
  SessionsRoute: typeof SessionsRoute
  StudentsRoute: typeof StudentsRoute
  TranscriptsRoute: typeof TranscriptsRoute
  ValidationAuditRoute: typeof ValidationAuditRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminFacultyAdminsRoute: typeof AdminFacultyAdminsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminProgrammesRoute: typeof AdminProgrammesRoute
  AdminRegistrationLinksRoute: typeof AdminRegistrationLinksRoute
  AdminResultPinsRoute: typeof AdminResultPinsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  DeptAdminApprovalsRoute: typeof DeptAdminApprovalsRoute
  DeptAdminAssignmentsRoute: typeof DeptAdminAssignmentsRoute
  DeptAdminDashboardRoute: typeof DeptAdminDashboardRoute
  DeptAdminLecturersRoute: typeof DeptAdminLecturersRoute
  DeptAdminLoginRoute: typeof DeptAdminLoginRoute
  FacultyCarryoversRoute: typeof FacultyCarryoversRoute
  FacultyCoursesRoute: typeof FacultyCoursesRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyDeptAdminsRoute: typeof FacultyDeptAdminsRoute
  FacultyLoginRoute: typeof FacultyLoginRoute
  FacultyRegistrationLinksRoute: typeof FacultyRegistrationLinksRoute
  FacultyResultEntryRoute: typeof FacultyResultEntryRoute
  FacultyResultsRoute: typeof FacultyResultsRoute
  FacultyStudentsRoute: typeof FacultyStudentsRoute
  FacultyTranscriptsRoute: typeof FacultyTranscriptsRoute
  LecturerDashboardRoute: typeof LecturerDashboardRoute
  LecturerEntryRoute: typeof LecturerEntryRoute
  LecturerLoginRoute: typeof LecturerLoginRoute
  ResultPinBuyRoute: typeof ResultPinBuyRoute
  ResultPinCallbackRoute: typeof ResultPinCallbackRoute
  StudentCarryoversRoute: typeof StudentCarryoversRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentPasswordRoute: typeof StudentPasswordRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
  StudentResultPinsRoute: typeof StudentResultPinsRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentServicesRoute: typeof StudentServicesRoute
  VerifyResultCodeRoute: typeof VerifyResultCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-audit': {
      id: '/validation-audit'
      path: '/validation-audit'
      fullPath: '/validation-audit'
      preLoaderRoute: typeof ValidationAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result-entry': {
      id: '/result-entry'
      path: '/result-entry'
      fullPath: '/result-entry'
      preLoaderRoute: typeof ResultEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-result': {
      id: '/check-result'
      path: '/check-result'
      fullPath: '/check-result'
      preLoaderRoute: typeof CheckResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-result/$code': {
      id: '/verify-result/$code'
      path: '/verify-result/$code'
      fullPath: '/verify-result/$code'
      preLoaderRoute: typeof VerifyResultCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/services': {
      id: '/student/services'
      path: '/student/services'
      fullPath: '/student/services'
      preLoaderRoute: typeof StudentServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/result-pins': {
      id: '/student/result-pins'
      path: '/student/result-pins'
      fullPath: '/student/result-pins'
      preLoaderRoute: typeof StudentResultPinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/register': {
      id: '/student/register'
      path: '/student/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/password': {
      id: '/student/password'
      path: '/student/password'
      fullPath: '/student/password'
      preLoaderRoute: typeof StudentPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/carryovers': {
      id: '/student/carryovers'
      path: '/student/carryovers'
      fullPath: '/student/carryovers'
      preLoaderRoute: typeof StudentCarryoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result-pin/callback': {
      id: '/result-pin/callback'
      path: '/result-pin/callback'
      fullPath: '/result-pin/callback'
      preLoaderRoute: typeof ResultPinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result-pin/buy': {
      id: '/result-pin/buy'
      path: '/result-pin/buy'
      fullPath: '/result-pin/buy'
      preLoaderRoute: typeof ResultPinBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/lecturer/login': {
      id: '/lecturer/login'
      path: '/lecturer/login'
      fullPath: '/lecturer/login'
      preLoaderRoute: typeof LecturerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/entry': {
      id: '/lecturer/entry'
      path: '/lecturer/entry'
      fullPath: '/lecturer/entry'
      preLoaderRoute: typeof LecturerEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/dashboard': {
      id: '/lecturer/dashboard'
      path: '/lecturer/dashboard'
      fullPath: '/lecturer/dashboard'
      preLoaderRoute: typeof LecturerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/transcripts': {
      id: '/faculty/transcripts'
      path: '/faculty/transcripts'
      fullPath: '/faculty/transcripts'
      preLoaderRoute: typeof FacultyTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/students': {
      id: '/faculty/students'
      path: '/faculty/students'
      fullPath: '/faculty/students'
      preLoaderRoute: typeof FacultyStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/results': {
      id: '/faculty/results'
      path: '/faculty/results'
      fullPath: '/faculty/results'
      preLoaderRoute: typeof FacultyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/result-entry': {
      id: '/faculty/result-entry'
      path: '/faculty/result-entry'
      fullPath: '/faculty/result-entry'
      preLoaderRoute: typeof FacultyResultEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/registration-links': {
      id: '/faculty/registration-links'
      path: '/faculty/registration-links'
      fullPath: '/faculty/registration-links'
      preLoaderRoute: typeof FacultyRegistrationLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/login': {
      id: '/faculty/login'
      path: '/faculty/login'
      fullPath: '/faculty/login'
      preLoaderRoute: typeof FacultyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dept-admins': {
      id: '/faculty/dept-admins'
      path: '/faculty/dept-admins'
      fullPath: '/faculty/dept-admins'
      preLoaderRoute: typeof FacultyDeptAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/courses': {
      id: '/faculty/courses'
      path: '/faculty/courses'
      fullPath: '/faculty/courses'
      preLoaderRoute: typeof FacultyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/carryovers': {
      id: '/faculty/carryovers'
      path: '/faculty/carryovers'
      fullPath: '/faculty/carryovers'
      preLoaderRoute: typeof FacultyCarryoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/login': {
      id: '/dept-admin/login'
      path: '/dept-admin/login'
      fullPath: '/dept-admin/login'
      preLoaderRoute: typeof DeptAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/lecturers': {
      id: '/dept-admin/lecturers'
      path: '/dept-admin/lecturers'
      fullPath: '/dept-admin/lecturers'
      preLoaderRoute: typeof DeptAdminLecturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/dashboard': {
      id: '/dept-admin/dashboard'
      path: '/dept-admin/dashboard'
      fullPath: '/dept-admin/dashboard'
      preLoaderRoute: typeof DeptAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/assignments': {
      id: '/dept-admin/assignments'
      path: '/dept-admin/assignments'
      fullPath: '/dept-admin/assignments'
      preLoaderRoute: typeof DeptAdminAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/approvals': {
      id: '/dept-admin/approvals'
      path: '/dept-admin/approvals'
      fullPath: '/dept-admin/approvals'
      preLoaderRoute: typeof DeptAdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack-webhook': {
      id: '/api/paystack-webhook'
      path: '/api/paystack-webhook'
      fullPath: '/api/paystack-webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/result-pins': {
      id: '/admin/result-pins'
      path: '/admin/result-pins'
      fullPath: '/admin/result-pins'
      preLoaderRoute: typeof AdminResultPinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registration-links': {
      id: '/admin/registration-links'
      path: '/admin/registration-links'
      fullPath: '/admin/registration-links'
      preLoaderRoute: typeof AdminRegistrationLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programmes': {
      id: '/admin/programmes'
      path: '/admin/programmes'
      fullPath: '/admin/programmes'
      preLoaderRoute: typeof AdminProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculty-admins': {
      id: '/admin/faculty-admins'
      path: '/admin/faculty-admins'
      fullPath: '/admin/faculty-admins'
      preLoaderRoute: typeof AdminFacultyAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/admin/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ApplyRoute: ApplyRoute,
  AuditLogsRoute: AuditLogsRoute,
  CheckResultRoute: CheckResultRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  ProgrammesRoute: ProgrammesRoute,
  ResultEntryRoute: ResultEntryRoute,
  ResultsRoute: ResultsRoute,
  SchoolsRoute: SchoolsRoute,
  SessionsRoute: SessionsRoute,
  StudentsRoute: StudentsRoute,
  TranscriptsRoute: TranscriptsRoute,
  ValidationAuditRoute: ValidationAuditRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminFacultyAdminsRoute: AdminFacultyAdminsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminProgrammesRoute: AdminProgrammesRoute,
  AdminRegistrationLinksRoute: AdminRegistrationLinksRoute,
  AdminResultPinsRoute: AdminResultPinsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  DeptAdminApprovalsRoute: DeptAdminApprovalsRoute,
  DeptAdminAssignmentsRoute: DeptAdminAssignmentsRoute,
  DeptAdminDashboardRoute: DeptAdminDashboardRoute,
  DeptAdminLecturersRoute: DeptAdminLecturersRoute,
  DeptAdminLoginRoute: DeptAdminLoginRoute,
  FacultyCarryoversRoute: FacultyCarryoversRoute,
  FacultyCoursesRoute: FacultyCoursesRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyDeptAdminsRoute: FacultyDeptAdminsRoute,
  FacultyLoginRoute: FacultyLoginRoute,
  FacultyRegistrationLinksRoute: FacultyRegistrationLinksRoute,
  FacultyResultEntryRoute: FacultyResultEntryRoute,
  FacultyResultsRoute: FacultyResultsRoute,
  FacultyStudentsRoute: FacultyStudentsRoute,
  FacultyTranscriptsRoute: FacultyTranscriptsRoute,
  LecturerDashboardRoute: LecturerDashboardRoute,
  LecturerEntryRoute: LecturerEntryRoute,
  LecturerLoginRoute: LecturerLoginRoute,
  ResultPinBuyRoute: ResultPinBuyRoute,
  ResultPinCallbackRoute: ResultPinCallbackRoute,
  StudentCarryoversRoute: StudentCarryoversRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentPasswordRoute: StudentPasswordRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRegisterRoute: StudentRegisterRoute,
  StudentResultPinsRoute: StudentResultPinsRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentServicesRoute: StudentServicesRoute,
  VerifyResultCodeRoute: VerifyResultCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
